export const ADICIONAR_PROJETO = 'ADICIONAR_PROJETO';
export const ALTERAR_PROJETO = 'ALTERAR_PROJETO';
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO';

export const NOTIFICAR = 'NOTIFICAR'
export const FECHAR_NOTIFICACAO = 'FECHAR_NOTIFICACAO'